- hosts: localhost
  vars:
    work_public_ssh_key: "work_github.pub"
    personal_public_ssh_key: "personal_github.pub"
  vars_prompt:
    - name: machine_type
      prompt: Machine personal or work?
      default: personal
      private: no
  pre_tasks:
    - name: Update Brew
      community.general.homebrew:
        update_homebrew: yes
      tags:
        - install
        - core
  tasks:
    - include_tasks: ansible/tasks/security.yaml
    - include_tasks: ansible/tasks/git-setup.yaml
    - include_tasks: ansible/tasks/cli-tools.yaml
    - include_tasks: ansible/tasks/gui-tools.yaml
    - include_tasks: ansible/tasks/zsh.yaml
    - include_tasks: ansible/tasks/app-store-apps.yaml
    # - include: ansible/tasks/fonts.yaml
    - include_tasks: ansible/tasks/osx.yaml
    - include_tasks: ansible/tasks/node.yaml
    - include_tasks: ansible/tasks/dotfiles.yaml
    - include_tasks: ansible/tasks/dock.yaml
