- name: Install CLI packages
  community.general.homebrew:
    name: "{{ item }}"
    state: latest
  ignore_errors: yes
  with_items:
    - tmux
    - fzf
    - z
    - gh
    - aria2
    - curl
    - wget
    - yarn
    - tree
    - thefuck
    - mas
    - starship
    - httpie
    - jq
    - lazygit
    - glances
    - tldr
    - fd
    - asciinema
    - exa
    - bat
    - robotsandpencils/made/xcodes
    - rust
  tags:
    - install
    - productivity
    - cli

- name: Better fzf shell integration
  ansible.builtin.shell: $(brew --prefix)/opt/fzf/install
  tags:
    - install
    - productivity
    - cli
