- name: Install dockutil
  ignore_errors: yes
  community.general.homebrew:
    name: ["hpedrorodrigues/tools/dockutil"]
  tags:
    - install
    - dock

- name: Clear dock
  shell: dockutil --remove all --no-restart
  tags:
    - install
    - dock

- name: Setup dock
  shell: dockutil --add {{ item }} --no-restart
  with_items:
    - /Applications/Home.app
    - "'' --type spacer --section apps --after Home"
    - /Applications/Visual\ Studio\ Code.app
    - /Applications/XCode.app
    - /Applications/Warp.app
    - "'' --type spacer --section apps --after Warp"
    - /Applications/Brave\ Browser.app
    - /Applications/Safari.app
    - /Applications/Firefox.app
    - "'' --type spacer --section apps --after Firefox"
    - /Applications/Drafts.app
    - /Applications/Obsidian.app
    - /Applications/Todoist.app
    - /Applications/1Password.app
    - "'' --type spacer --section apps --after 1Password"
    - /Applications/Mail.app
    - /Applications/Calendar.app
    - /Applications/Messages.app
    - /Applications/Slack.app
    - /Applications/Discord.app
    - "'' --type spacer --section apps --after Discord"
    - /Applications/Music.app
    - /Applications/Podcasts.app
  ignore_errors: yes
  tags:
    - install
    - dock

- name: Restart dock
  shell: "/usr/bin/killall Dock"
  tags:
    - install
    - dock
