- name: Install stow
  community.general.homebrew:
    name: ["stow"]
  tags:
    - install
    - dotfiles
    - stow
    - cli

- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: "https://github.com/mintuz/.dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    force: yes
    version: master
  tags:
    - install
    - dotfiles
    - stow
    - cli

- name: Cloning tpm (tmux plug manager)
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"
    recursive: yes
    update: yes
    accept_hostkey: yes
    force: yes
    version: master
  tags:
    - install
    - dotfiles
    - stow
    - cli

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./install.sh
  changed_when: true
  tags:
    - install
    - dotfiles
    - stow
    - cli

- name: Check for presence of .tmux.conf
  stat:
    path: ~/.tmux.conf
  register: tmux_conf_exists
  tags:
    - install
    - dotfiles
    - stow
    - cli
