- name: Install latest Git
  community.general.homebrew:
    name: git
    state: latest
  tags:
    - git-personal

- name: Create global .gitignore
  ansible.builtin.template:
    src: ../templates/.global_gitignore
    dest: ~/.global_gitignore
    mode: "0644"
  tags:
    - git-personal

- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "mintuz1990@gmail.com"
  tags:
    - git-personal

- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "Adam Bulmer"
  tags:
    - git-personal

- name: Git set pull to rebase
  git_config:
    name: pull.rebase
    scope: global
    value: "true"
  tags:
    - git-personal

- name: Set global git ignore
  community.general.git_config:
    name: core.excludesfile
    scope: global
    value: ~/.global_gitignore
  tags:
    - git-personal

- name: Set git fetch to always prune
  community.general.git_config:
    name: fetch.prune
    scope: global
    value: "true"
  tags:
    - git-personal

- name: Set global git default branch name
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: main
  tags:
    - git-personal

- name: Set autoSetupRemote to true to automatically set upstream branch on push
  community.general.git_config:
    name: push.autoSetupRemote
    scope: global
    value: "true"
  tags:
    - git-personal
