- name: Install Apps
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: latest
  ignore_errors: yes
  with_items:
    # Mac Uiltiies
    - appcleaner
    - downie
    - unclack
    - cleanshot
    - bettertouchtool
    - bartender
    - istat-menus
    - raycast
    - lunar
    - gas-mask
    - amethyst
    - rectangle-pro
    - alt-tab
    - popclip
    - steelseries-gg
    # Software Development
    - paw
    - warp
    - visual-studio-code
    # App Development
    - rotato
    - blender
    - unity-hub
    # Web Development
    - brave-browser
    - arc
    - firefox
    # PKM
    - obsidian
    - dropbox
    # Social
    - discord
    - zoom
    - slack
    - camo-studio
    # Design
    - sketch
    # Misc
    - vlc
    - little-navmap
  tags:
    - install
    - gui
    - productivity
