- name: Install Apps
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: latest
  ignore_errors: yes
  with_items:
    # Mac Uiltiies
    - appcleaner
    - downie
    - unclack
    - cleanshot
    - bettertouchtool
    - istat-menus
    - raycast
    - lunar
    - gas-mask
    - jordanbaird-ice
    - rectangle-pro
    - alt-tab
    - popclip
    - protonvpn
    # Software Development
    - paw
    - warp
    - tabby
    - visual-studio-code
    - cursor
    - zed
    # App Development
    - rotato
    # Web Development
    - vivaldi
    - arc
    - firefox
    # PKM
    - obsidian
    - dropbox
    - proton-mail
    - proton-drive
    # Social
    - discord
    - zoom
    - slack
    - camo-studio
    # Design
    - sketch
    # Misc
    - vlc
    - steam
  tags:
    - install
    - gui
    - productivity
