- name: Install Apps
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: latest
  ignore_errors: yes
  with_items:
    - appcleaner
    - downie
    - rotato
    - google-chrome
    - brave-browser
    - firefox
    - discord
    - zoom
    - slack
    - unclack
    - gas-mask
    - sketch
    - paw
    - warp
    - visual-studio-code
    - cleanshot
    - bettertouchtool
    - bartender
    - istat-menus
    - camo-studio
    - raycast
    - popclip
    - obsidian
  tags:
    - install
    - gui
    - productivity
# - name: Install Latest XCode
#   ansible.builtin.shell: xcodes install --latest --experimental-unxip
#   tags:
#     - install
#     - gui
#     - xcode
#     - productivity

# - name: Install XCode Beta
#   ansible.builtin.shell: xcodes install --latest-prerelease --experimental-unxip
#   tags:
#     - install
#     - gui
#     - xcode
#     - productivity
