- name: Install nvm
  community.general.homebrew:
    name: nvm
    state: latest
  tags:
    - install
    - node

- name: Install latest lts version of node
  ansible.builtin.shell: |
    source ~/.zshrc
    nvm install --lts
    nvm alias default
  tags:
    - install
    - node

- name: Check if github-copilot-cli is installed
  ansible.builtin.command: github-copilot-cli --version
  register: github_copilot_cli_check
  ignore_errors: true
  changed_when: false
  tags:
    - install
    - node

- name: Install Github CoPilot cli globally with npm
  ansible.builtin.shell: |
    source ~/.zshrc
    npm install -g @githubnext/github-copilot-cli
  args:
    executable: /bin/zsh
  when: github_copilot_cli_check.rc != 0
  tags:
    - install
    - node
