# Useful list of defaults: https://macos-defaults.com/finder/fxremoveoldtrashitems.html#set-to-true
- name: Setup OSX Settings
  shell: "{{ item }}"
  with_items:
    # Show Path bar in Finder
    - defaults write com.apple.finder ShowPathbar -bool true
    # Show Status bar in Finder
    - defaults write com.apple.finder ShowStatusBar -bool true

    # Show icons for hard drives, servers, and removable media on the desktop
    - defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
    - defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
    - defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
    - defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

    # Show absolute path in finder's title bar.
    - defaults write com.apple.finder _FXShowPosixPathInTitle -bool YES

    # Show the ~/Library folder
    - chflags nohidden ~/Library

    # Set default Finder location to home folder (~/)
    - defaults write com.apple.finder NewWindowTarget -string "PfLo"
    - defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}"

    # Use current directory as default search scope in Finder
    - defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

    # show all filename extensions
    - defaults write NSGlobalDomain AppleShowAllExtensions -bool true

    # Disable ext change warning
    - defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

    # General UI/UX
    # ----------------------------------------------------------------------

    # Always show scrollbars
    - defaults write NSGlobalDomain AppleShowScrollBars -string "Always"

    # Set a blazingly fast keyboard repeat rate
    - defaults write NSGlobalDomain KeyRepeat -int 0

    # Dock: position the Dock on the left
    - defaults write com.apple.dock orientation left

    # Dock: show indicator lights for open applications
    - defaults write com.apple.dock show-process-indicators -bool true

    # Dock: make icons of hidden applications translucent
    - defaults write com.apple.dock showhidden -bool true

    # Dock: don’t animate opening applications
    - defaults write com.apple.dock launchanim -bool false

    # Dock: use the scale effect for window minimizing
    - defaults write com.apple.dock mineffect scale

    # Dock: speed up Mission Control animations
    - defaults write com.apple.dock expose-animation-duration -float 0.1

    ## Dock: Hide Dock
    - defaults write com.apple.dock autohide -bool false

    # Dock: Remove animation delay
    - defaults write com.apple.dock autohide-delay -float 0

    # Finder: empty Trash securely by default
    - defaults write com.apple.finder EmptyTrashSecurely -bool true

    # Finder: disable window and Get Info animations
    - defaults write com.apple.finder DisableAllAnimations -bool true

    # Finder: allow quitting via ⌘ + Q; doing so will also hide desktop icons
    - defaults write com.apple.finder QuitMenuItem -bool true

    # Finder: show hidden files by default
    - defaults write com.apple.finder AppleShowAllFiles -bool true

    # Finder: use list view in all windows by default
    # Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`
    - defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

    # Panels
    # ----------------------------------------------------------------------

    # Panels: expand save panel by default
    - defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true

    # Panels: expand print panel by default
    - defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true

    # Panels: disable the “Are you sure you want to open this application?” dialog
    - defaults write com.apple.LaunchServices LSQuarantine -bool false

    # Panels: enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)
    - defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

    # Screen
    # ----------------------------------------------------------------------

    # Screen: require password immediately after sleep or screen saver begins
    - defaults write com.apple.screensaver askForPassword -int 1
    - defaults write com.apple.screensaver askForPasswordDelay -int 0

    # Screen: save screenshots to the desktop
    - defaults write com.apple.screencapture location -string "$HOME/Desktop"

    # Screen: disable shadow in screenshots
    - defaults write com.apple.screencapture disable-shadow -bool true

    # Screen: enable subpixel font rendering on non-Apple LCDs
    - defaults write NSGlobalDomain AppleFontSmoothing -int 2

    # Misc
    # ----------------------------------------------------------------------

    # Misc: disable Dictionary results
    - defaults write com.apple.spotlight DictionaryLookupEnabled -bool false

    # Misc: disable auto-correct
    - defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
  tags:
    - install
    - osx

- name: Configure terminal to open in same directory by default
  shell: defaults write com.apple.Terminal NewTabWorkingDirectoryBehavior -bool true
  tags:
    - install
    - osx

- name: Set Automatic Software Updates To True
  osx_defaults:
    domain: /Library/Preferences/com.apple.SoftwareUpdate
    key: AutomaticCheckEnabled
    type: int
    value: 1
  become: yes
  tags:
    - install
    - osx

- name: Restart finder
  changed_when: true
  command: killall Finder
  tags:
    - install
    - osx
